version: '3.5'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      network: host
    env_file:
      - .env.docker
    image: sanjumsanthosh/student-tracker:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8083:8081"